server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /myPages/**
        - id: activation
          uri: http://localhost:8082
          predicates:
            - Path=/activations/** 
        - id: scheduling
          uri: http://localhost:8083
          predicates:
            - Path=/schedulings/** 
        - id: fieldwork
          uri: http://localhost:8084
          predicates:
            - Path=/fieldWorks/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://oss-order:8080
          predicates:
            - Path=/orders/**, /myPages/**
        - id: activation
          uri: http://oss-activation:8080
          predicates:
            - Path=/activations/** 
        - id: scheduling
          uri: http://oss-scheduling:8080
          predicates:
            - Path=/schedulings/** 
        - id: fieldwork
          uri: http://oss-fieldwork:8080
          predicates:
            - Path=/fieldWorks/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
